spring:
  application:
    name: product
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: debug
