spring:
  application:
    name: order-service
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
  redis:
    host: localhost
    port: 6379
    password: 123456
  sleuth:
    sampler:
      probability: 1
  zipkin:
    sender:
      type: web # 真鸡儿坑...
    base-url: http://localhost:9411/
    
# ribbon全局配置
ribbon:
  eager-load:
    # 开启ribbon的饥饿模式 避免首次调用时超时
    enabled: true
    # 指定饥饿加载的服务名称
    clients: product-service
# ribbon指定服务配置超时判定，优先级更高
product-service:
  ribbon:
    # 负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    # 每台机器最大重试次数
    MaxAutoRetries: 0
    # 可以再重试几台机器
    MaxAutoRetriesNextServer: 0
    # 连接超时
    ConnectTimeout: 1000
    # 业务处理超时
    ReadTimeout: 2000
    # 在所有的Http Method上进行重试
    OkToRetryOnAllOperations: false
    
# feign超时判定，优先级高于ribbon
feign:
  client:
    config:
      # 全局默认配置
      default:
        connectTimeout: 1000
        readTimeout: 5000
      # 指定服务配置，优先级更高
      product-service:
        connectTimeout: 1000
        readTimeout: 8000
  hystrix:
    # 开启Hystrix
    enabled: true
    
hystrix:
  command:
    default:
      fallback:
        # 开启服务降级
        enabled: true
      execution:
        timeout:
          # 全局超时
          enabled: true
        isolation:
          thread:
            # 超时时间
            timeoutInMilliseconds: 3000
            # 超时以后是否终止线程
            interruptOnTimeout: true
            # 取消的时候是否终止线程
            interruptOnCancel: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
        
logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: debug
          
env:
  name: dev
