spring:
  application:
    name: product-service
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
      
logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: debug

# actuator开放端口
management:
  endpoints:
    web:
      exposure:
        include: "*"

# feign超时判定，优先级高于ribbon
feign:
  client:
    config:
      # 全局默认配置
      default:
        connectTimeout: 1000
        readTimeout: 5000
      # 指定服务配置，优先级更高
      product-service:
        connectTimeout: 1000
        readTimeout: 8000
