spring:
  application:
    name: user
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
